services:
  - type: web
    name: sisfitkids-api
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: SESSION_COOKIE_SAMESITE
        value: "None"
      - key: CSRF_COOKIE_SAMESITE
        value: "None"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
