# Generated by Django 5.2.14 on 2026-07-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classgroup_student_class_group_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default='SIS Fit Kids', max_length=120, verbose_name='academia')),
                ('teacher_name', models.CharField(default='Profesor Principal', max_length=120, verbose_name='profesor')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('address', models.CharField(blank=True, max_length=180, verbose_name='direccion')),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='mensualidad por defecto')),
            ],
            options={
                'verbose_name': 'configuracion',
                'verbose_name_plural': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('body', models.TextField(verbose_name='mensaje')),
                ('audience', models.CharField(choices=[('ALL', 'Todos'), ('PARENT', 'Padre especifico')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.parentprofile')),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.classgroup')),
            ],
            options={
                'verbose_name': 'sesion de asistencia',
                'verbose_name_plural': 'sesiones de asistencia',
                'ordering': ['-date', 'class_group__day_of_week'],
                'unique_together': {('class_group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProgressEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso kg')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='talla cm')),
                ('strength', models.PositiveSmallIntegerField(default=0, verbose_name='fuerza')),
                ('endurance', models.PositiveSmallIntegerField(default=0, verbose_name='resistencia')),
                ('coordination', models.PositiveSmallIntegerField(default=0, verbose_name='coordinacion')),
                ('flexibility', models.PositiveSmallIntegerField(default=0, verbose_name='flexibilidad')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_evaluations', to='core.student')),
            ],
            options={
                'verbose_name': 'evaluacion de progreso',
                'verbose_name_plural': 'evaluaciones de progreso',
                'ordering': ['-date', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Falta'), ('LATE', 'Tardanza'), ('JUSTIFIED', 'Justificado')], default='PRESENT', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=160, verbose_name='notas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession')),
            ],
            options={
                'verbose_name': 'registro de asistencia',
                'verbose_name_plural': 'registros de asistencia',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
