# Generated by Django 5.2.14 on 2026-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appsetting_announcement_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='color',
            field=models.CharField(default='#0d7467', max_length=20, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, verbose_name='dias'),
        ),
    ]
